version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/prepare_db.sql:/docker-entrypoint-initdb.d/prepare_db.sql
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres

volumes:
  pgdata:
  pgadmin-data:

networks:
  postgres:
    driver: bridge